# Generated by Django 5.2.3 on 2025-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_last_completed_habit_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
