# Generated by Django 5.2.3 on 2025-06-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='emoji',
            field=models.CharField(blank=True, default='🌱', max_length=10),
        ),
    ]
