# Generated by Django 5.2.3 on 2025-06-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_reward_emoji_userreward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='emoji',
        ),
        migrations.AddField(
            model_name='reward',
            name='effect_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('daily_break', 'Día de Descanso'), ('streak_booster', 'Impulso de Racha'), ('theme', 'Tema Especial'), ('achievement', 'Logro Destacado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userreward',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
