# Generated by Django 5.2.1 on 2025-06-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_reward_emoji_reward_effect_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitprogress',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
