# Generated by Django 5.2.1 on 2025-06-18 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habitprogress_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badges', models.JSONField(blank=True, default=list)),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('nature', 'Naturaleza'), ('ocean', 'Océano')], default='light', max_length=20)),
                ('theme_expires', models.DateField(blank=True, null=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('highlight_expires', models.DateField(blank=True, null=True)),
                ('achievements', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
