# Generated by Django 5.2.1 on 2025-06-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_achievement_remove_userreward_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='highlight_expires',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_highlighted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theme_expires',
        ),
    ]
